name    'desalvo-emi'
version '0.1.0'
source 'https://github.com/desalvo/puppet-emi'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet modules for emi'
description 'Puppet modules to handle emi grid middleware configurations'
project_page 'https://github.com/desalvo/puppet-emi'

dependency 'desalvo/yumconfig', '>= 0.1.0 < 1.0.0'
